### ISSUE TITLE
Add metrics-collector infrastructure

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-metrics-collector#1]
_From @sabbyanandan on March 12, 2017 22:48_

As a user, I'd like to have a `metrics-collector` application, so I can consume, aggregate, and persist channel metrics across all the streams.

**Acceptance:**
- application consumes and aggregates real-time channel metrics between the apps that can be identified by stream name + destination
- application persists real-time metrics in memory by default with the flexibility for extensions
- app generated for the supported binders

_Copied from original issue: spring-cloud-stream-app-starters/app-starters-release#68_

**Comment by markpollack** [comment]
@sabbyanandan What does "app listed in the app descriptor file for bulk imports" mean?

**Comment by markpollack** [comment]
Some items that are out of scope

* Return format of the JSON will not be of the form returned by typical Spring Data REST Repositories. 
* The expiry of stale entries will not be implemented.

These will be done in as separate issues.

**Comment by sabbyanandan** [comment]
@markpollack ah, I moved this issue from app-starters and that's why the bulk import relevance. I removed it from the acceptance.
