### ISSUE TITLE
Add CI plan for metrics-collector

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-metrics-collector#2]
As a developer, I'd like to add CI plan for the metrics-collector.

**Acceptance:**
New CI plan available for continuous functionality verification.

**Comment by markpollack** [comment]
Need to use jenkins due to app generation procedure.

**Comment by markpollack** [comment]
Note, when https://github.com/spring-cloud/spring-cloud-dataflow-metrics-collector/pull/21 is merged he `-Pfull` profile would need to be enabled.  Not sure if there are any issues wrt to the CI plan and how the docs get published.

**Comment by sobychacko** [comment]
GH trigger is already in place.
docs build is enabled `(-Pfull)` using the artifactory plugin. Build info here: https://jenkins.spring.io/view/Seeds/job/spring-cloud-dataflow-metrics-collector-master-ci/
