### ISSUE TITLE
Stored metrics values that are older than a configurable timeout, will be removed.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-metrics-collector#5]
As streams are destroyed or recreated, the metric values from previously running instances will still be in stored in metrics collector.  These 'ghost entries' need to be removed.  A TTL value that is by default 2-3x the metrics emitter publishing interval is probably good heuristic value.

**Comment by viniciusccarvalho** [comment]
This was actually closed by 1c1951408c4416d15d162ec0e6d186e1fe15eabd
