### ISSUE TITLE
Add SCSt 2.0 and Micrometer compatibility

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-metrics-collector#51]
As a developer, I'd like to upgrade to SCSt 2.0, so I can bring Micrometer compatibility.

**Background:**
Boot 1.x based `Metric` infrastructure is replaced with Micrometer in the 2.0 release. SCSt 2.0 builds on the new foundation already. The goal is to convert `metrics-collector` into another SCSt 2.0 consumer/sink. 

**Acceptance:**
- Refactor and adapt to new infrastructure
- The collector functionally provides (via REST) the same data structure currently available in 1.x
- The newer Meter components and extra stats are "added" on top of it
- REST endpoints continue to operate against the same user credentials
- Unit/IT tests are refactored to adapt to the new infrastructure
- Migration guide provided (if necessary)

**Comment by tzolov** [comment]
This story depends on https://github.com/spring-projects/spring-boot/pull/12594
Later enables the Spring Integration micrometer integration required to compute the stream rates.

**Comment by sabbyanandan** [comment]
We would also have to review the operational specifics of `router-sink` as part of this effort. Based on the findings and the complexity, we can split it into a different story.

**Comment by sabbyanandan** [comment]
Also, note, we do not have any specifical handling in Flo for `router-sink`, so that's something we need to take into account as well.
